DROP DATABASE CHAT_DATA;
CREATE DATABASE CHAT_DATA;
USE CHAT_DATA;

DROP TABLE if exists USERS;
CREATE TABLE USERS(
    `username` VARCHAR (35) NOT NULL UNIQUE PRIMARY KEY DEFAULT "John",
    `password` VARCHAR (35) NOT NULL UNIQUE DEFAULT "Doe",
    `online` BOOLEAN DEFAULT 0     
);

DROP TABLE if exists ROOM;
CREATE TABLE ROOM(
    `id` INTEGER PRIMARY KEY AUTO_INCREMENT,
    `roomname` VARCHAR (35) UNIQUE DEFAULT "Game",
    `createdAt` TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

DROP TABLE if exists chatlogs;
CREATE TABLE chatlogs(
    `id` INTEGER NOT NULL DEFAULT 0 ,
	`username` VARCHAR (35),
    `message` VARCHAR(500) NOT NULL,	
    `createdAt` TIMESTAMP DEFAULT CURRENT_TIMESTAMP PRIMARY KEY,
    FOREIGN KEY (username) REFERENCES USERS(username)
    ON DELETE CASCADE,
    FOREIGN KEY (id) REFERENCES ROOM(id)
    ON DELETE CASCADE
);
